name: Release

on:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    name: Zig ${{ matrix.zig }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - if: matrix.os == 'windows-latest'
        name: Build
        run: zig build -Doptimize=ReleaseFast -j4
      - if: matrix.os == 'macos-latest'
        name: Build
        run: zig build -Doptimize=ReleaseFast -j4
      - if: matrix.os == 'ubuntu-latest'
        name: Build
        run: zig build -Dtarget="x86_64-linux-gnu.2.17" -Doptimize=ReleaseFast -j4
